spring.application.name=project-management
server.port=8082

spring.datasource.url=jdbc:mariadb://localhost:3306/project-management
spring.datasource.username=refill
spring.datasource.password=refill
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Log directory
#logging.file.name=/var/seamless/log/employee-management/employee-management.log

app.logging.directory=/var/seamless/log/project-management/
# Log levels
#logging.level.root=INFO
#logging.level.com.yourcompany.myapp=INFO

# Log4j2 rolling configuration
#logging.log4j2.rollingpolicy.file-name-pattern=/var/seamless/log/employee-management/application-%d{yyyy-MM-dd}-%i.log.gz
#logging.log4j2.rollingpolicy.max-file-size=100MB
#logging.log4j2.rollingpolicy.max-history=10
#logging.log4j2.rollingpolicy.strategy=size-and-time
#logging.log4j2.rollingpolicy.time-interval=1
#logging.log4j2.rollingpolicy.time-modulate=true

logging.config=classpath:log4j2-spring.xml